### PR TITLE
Fix typo double "at"

### PR DESCRIPTION
**Pull request by Olitelkes**
Fix typo double "at" in comment

### CODE REVIEW

**Comment by Olitelkes** [comment]
any update ?

**Comment by kkonevets** [comment]
I don't think this typo is worth a pull request

**Comment by Olitelkes** [comment]
just wanted to help, at least you are aware now, have a good day

**Comment by xhjkl** [comment]
Hi, @Olitelkes! At Solido, we strive our best to remain open and welcoming for the community, and I appreciate your time and intention you put into your correction.

Good eye, and thank you!

**Review by Shi-eld — APPROVED** [review]

**Comment by xhjkl** [comment]
Apparently, I cannot merge in your changes easily. If you prefer, you might want to rebase your changes against the current `main`. If you've lost interest in this PR, no worries — I'll apply your changes myself, but I still would love it if you could get proper attribution from Github by merging this one.

**Comment by xhjkl** [comment]
All right, this is clearly abandoned.

I've applied your changes at #19, so now hoping Github will pick it up as your contribution. If you have anything else, please feel free to open a new PR, and I might not monitor the closed ones.

**Comment by Olitelkes** [comment]
Thank you :)

**Pull request closed without merging**
